mxonline/apps/courses/urls.py
# _*_ coding: utf-8 _*_
_author__ = 'marshen'
__date__ = '2019/2/23 16:20'

from .views import CourseView,CourseDetailView,CourseVideoView,CourseCommentView,AddCommentView,VideoPlayView
from django.conf.urls import url,include


urlpatterns = [
    url('^list/$',CourseView.as_view(),name="list"),
    url('^detail/(?P<course_id>\d+)', CourseDetailView.as_view(), name="detail"),
    url('^video/(?P<course_id>\d+)', CourseVideoView.as_view(), name="video"),
    url('^comment/(?P<course_id>\d+)', CourseCommentView.as_view(), name="comment"),
    #添加课程评论  参数已经放入 post 里了所以不用加参数了
    url('^add_comment/$', AddCommentView.as_view(), name="add_comment"),
    url('^play_video/(?P<video_id>\d+)', VideoPlayView.as_view(), name="play_video"),
]

mxonline/apps/organization/urls.py
# _*_ coding: utf-8 _*_
_author__ = 'marshen'
__date__ = '2019/2/21 23:11'

from .views import OrgListView,AddUserAskView,OrgHomeView,OrgCourseView,OrgDescView,OrgTeacherView,AddFavView,TeacherListView,TeacherDetailView
from django.conf.urls import url,include


urlpatterns = [
    url('^list/$',OrgListView.as_view(),name="list"),
    url('^add_ask/$',AddUserAskView.as_view(),name="add_ask"),
    url('^home/(?P<org_id>\d+)',OrgHomeView.as_view(),name="org_home"),
    url('^course/(?P<org_id>\d+)',OrgCourseView.as_view(),name="org_course"),
    url('^desc/(?P<org_id>\d+)',OrgDescView.as_view(),name="org_desc"),
    url('^teacher/(?P<org_id>\d+)',OrgTeacherView.as_view(),name="org_teacher"),
    #机构收藏
    url('^add_fav/$', AddFavView.as_view(), name="add_fav"),

    url('^teacher_list/$',TeacherListView .as_view(), name="teacher_list"),
    url('^teacher_detail/(?P<teacher_id>\d+)',TeacherDetailView .as_view(), name="teacher_detail"),

]

mxonline/apps/users/urls.py
# _*_ coding: utf-8 _*_
_author__ = 'marshen'
__date__ = '2019/2/23 16:20'

from .views import UserCenterView,UserFavCourseCenterView,UserFavOrgCenterView,UserFavTeacherCenterView,UserMessageCenterView,UserMyCourseView,UpLoadImageView,UpdatePwdView,SendEmailView,UpdateEmailView,UserInfoSaveView
from django.conf.urls import url,include


urlpatterns = [

    url('^info/(?P<user_id>\d+)', UserCenterView.as_view(), name="info"),

    url('^fav_course/(?P<user_id>\d+)', UserFavCourseCenterView.as_view(), name="fav_course"),

    url('^my_course/(?P<user_id>\d+)', UserMyCourseView.as_view(), name="my_course"),

    url('^fav_org/(?P<user_id>\d+)', UserFavOrgCenterView.as_view(), name="fav_org"),

    url('^fav_teacher/(?P<user_id>\d+)', UserFavTeacherCenterView.as_view(), name="fav_teacher"),

    url('^my_messages/(?P<user_id>\d+)', UserMessageCenterView.as_view(), name="my_messages"),

    #用户头像上传
    url('^image/upload/$', UpLoadImageView.as_view(), name="image_upload"),
    #用户个人中心修改密码
    url('^update/pwd/$', UpdatePwdView.as_view(), name="update_pwd"),
    #修改邮箱 发送验证码
    url('^sendemail_code/$', SendEmailView.as_view(), name="sendemail_code"),
    url('^update_email/$', UpdateEmailView.as_view(), name="update_email"),

    url('^info_save/$', UserInfoSaveView.as_view(), name="info_svae"),

]


#全局404界面
handler404 = 'user.view.page_not_found'
#要在seeting中將debug設置為false
handler500 = 'user.view.page_error'

mxonline/mxonline/urls.py
# -*- coding: utf-8 -*-
"""mxonline URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url,include
from django.contrib import admin
from django.views.generic import TemplateView
from django.views.static import serve

# from users.views import user_login
from users.views import LoginView,RegisterView,ActiveUserView,ForgetPwdView,ResetView,ModifyPwdView,LogOutView,IndexView
from organization.views import OrgListView
from mxonline.settings import MEDIA_ROOT,STATIC_ROOT
import xadmin

urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),
    url('^$',IndexView.as_view(),name="index"),
    # url('^login/$',user_login,name="login",)
    #调用login()——>render()函数，返回view对象
    url('^login/$',LoginView.as_view(),name="login"),
    url('^logout/$', LogOutView.as_view(), name="logout"),
    #基于类的view书写,注册register界面
    url('^register/$',RegisterView.as_view(),name="register"),
    url(r'^captcha/', include('captcha.urls')),
    #注册验证码url
    url(r'^active/(?P<active_code>.*)/$',ActiveUserView.as_view(),name="user_active"),
    # 获取active_code

    url(r'^forget/$', ForgetPwdView.as_view(), name="forget"),
    url(r'^reset/(?P<reset_code>.*)/$', ResetView.as_view(), name="reset_pwd"),


    url(r'^modify_pwd/$', ModifyPwdView.as_view(), name="modify_pwd"),

    url(r'^org/', include('organization.urls',namespace="org")),
    url(r'^course/', include('courses.urls',namespace="course")),

    url(r'^usercenter/', include('users.urls', namespace="usercenter")),

    #处理org_list.html 文件中的logo url的问题
    url(r'^media/(?P<path>.*)/$',serve,{"document_root":MEDIA_ROOT}),

    url(r'^static/(?P<path>.*)/$', serve, {"document_root": STATIC_ROOT})

]


mxonline/apps/courses/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from datetime import datetime

from organization.models import CoursesOrg,Teacher
from django.db import models

# Create your models here.


class Course(models.Model):
    org = models.ForeignKey(CoursesOrg,verbose_name=u"课程机构")
    teacher = models.ForeignKey(Teacher,verbose_name="教学老师")
    name = models.CharField(max_length=50,verbose_name=u"课程名")
    desc = models.CharField(max_length=300,verbose_name=u"课程描述")
    detail = models.TextField(verbose_name=u"课程详情")
    degree = models.CharField(verbose_name=u"难度",choices=(("cj","初级"),("zj","中级"),("gj","高级")),max_length=5)
    learn_time = models.IntegerField(default=0,verbose_name=u"学习时长（分钟）")
    students = models.IntegerField(default=0,verbose_name=u"学习人数")
    fav_nums =models.IntegerField(default=0,verbose_name=u"收藏人数")
    image = models.ImageField(upload_to="courses/%Y/%m",verbose_name=U"封面")
    click_num = models.IntegerField(default=0,verbose_name=u"点击数")
    add_time = models.DateTimeField(default=datetime.now,verbose_name=u"添加时间")
    category = models.CharField(max_length=20, verbose_name=u"课程类别",default="后端开发")
    tag = models.CharField(max_length=10, verbose_name=u"标签",default="")
    notice =  models.CharField(max_length=100, verbose_name=u"课程公告",default="")
    teacher_tell = models.CharField(max_length=100, verbose_name=u"老师告诉你",default="")
    youneed_konw = models.CharField(max_length=100, verbose_name=u"须知",default="")
    is_banner = models.BooleanField(default=False,verbose_name=u"是否輪播")
    class Meta:
        verbose_name = u"课程"
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.name
    def get_lesson_nums(self):
        return len(self.lesson_set.all())

    def get_course_lesson(self):
        return self.lesson_set.all()

        return
    def get_learner(self):
        """获取课程用户
        前端代码{% for user_course in course_detail.get_learner %}
        {{ MEDIA_URL }}{{ user_course.user.image}}
        获取learner的头像
        course  与user 通过usercourse进行关联


        """
        return self.usercourse_set.all()[:5]


class Lesson(models.Model):
    course = models.ForeignKey(Course,verbose_name=u"课程")
    name = models.CharField(max_length=100,verbose_name=u"章节名")
    add_time = models.DateTimeField(default= datetime.now,verbose_name=u"添加时间")

    class Meta:
        verbose_name = u"章节"
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.name
    def get_lesson_video(self):
        return self.video_set.all()







class Video(models.Model):
    lesson =models.ForeignKey(Lesson,verbose_name=u"章节")
    name = models.CharField(max_length=100,verbose_name=u"视频")
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u"添加时间")
    learn_time = models.IntegerField(default=0,verbose_name=u"学习时长（分钟）")
    url = models.CharField(max_length=500,verbose_name=u"视频链接",default="")
    class Meta:
        verbose_name = u"视频"
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.name

class CourseResourse(models.Model):
    course = models.ForeignKey(Course,verbose_name=u"课程")
    name = models.CharField(max_length=100,verbose_name=u"课程资源")
    download = models.FileField(upload_to="course/resourse/%Y%m",verbose_name=u"下载",max_length=100)

    add_time = models.DateTimeField(default=datetime.now, verbose_name=u"添加时间")

    class Meta:
        verbose_name = u"课程资源"
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.name

mxonline/templates/active_fail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>链接失效</p>
</body>
</html>

mxonline/templates/course-video.html

{% extends 'base.html' %}

{% load staticfiles %}
{% block title %}
课程视频
{% endblock %}
{% block custom_bread %}
  <section>
	<div class="wp">
		<div class="crumbs">
			<ul>
				<li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'course:list' %}">公开课程</a>></li>
				<li><a href="">课程详情</a>></li>
                <li>章节信息</li>
			</ul>
		</div>
	</div>
</section>

{% endblock %}

{% block content %}

<div id="main">
{% block play_area %}
    <div class="course-infos">
        <div class="w pr">
            <div style="height: 15px" class="path">
            </div>
            <div class="hd">
                <h2 class="l">{{ course.name }}</h2>
            </div>
            <div class="statics clearfix">
                <div class="static-item ">
                    <span class="meta-value"><strong>{{ course.get_degree_display }}</strong></span>
                    <span class="meta">难度</span>
                    <em></em>
                </div>
                <div class="static-item static-time">
                    <span class="meta-value">{{ course.learn_time }}分钟</span>
                    <span class="meta">时长</span>
                    <em></em>
                </div>
                <div class="static-item">
                    <span class="meta-value"><strong>{{ course.students }}</strong></span>
                    <span class="meta">学习人数</span>
                    <em></em>
                </div>
            </div>
        </div>
    </div>

{% endblock %}



    <div class="course-info-main clearfix w has-progress">

        <div class="info-bar clearfix">
        <div class="content-wrap clearfix">
            <div class="content">
                <div class="mod-tab-menu">
                    <ul class="course-menu clearfix">
                        <li><a class="{% if current_page == 'video' %}
                        active
                        {% endif %}" id="learnOn"  href="{% url 'course:video' course.id %}"><span>章节</span></a></li>
                        <li><a id="commentOn" class="{% if current_page == 'comment' %}
                        active
                        {% endif %}" href="{% url 'course:comment' course.id %}"><span>评论</span></a></li>
                    </ul>
                </div>



            {% block main_area %}
                            <div id="notice" class="clearfix">

                    <div class="l"> <strong>课程公告:</strong> <a  href="javascript:void(0)">{{ course.notice }}</a> </div>

                </div>


                <div class="mod-chapters">

{% for lesson in course.get_course_lesson %}
<div class="chapter chapter-active" >

                        <h3>
                            <strong><i class="state-expand"></i>{{ lesson.name }}</strong>
                        </h3>

                        <ul class="video">
                                {% for video in lesson.get_lesson_video %}
                                                  <li>
                                <a target="_blank" href="{% url 'course:play_video' video.id %}" class="J-media-item studyvideo">{{ video.name }}
                                    <i class="study-state"></i>
                                </a>
                            </li>

                                {% endfor %}

                        </ul>
                    </div>
{% endfor %}
{#章节内容#}
                </div>

            {% endblock %}



            </div>
            <div class="aside r">
                <div class="bd">

                    <div class="box mb40">
                        <h4>资料下载</h4>
                        <ul class="downlist">
                    {% for resourse in all_resourse %}
                                                <li>
                                <span ><i class="aui-iconfont aui-icon-file"></i>&nbsp;&nbsp;{{ resourse.name }}</span>
                                <a href="{{ MEDIA_URL }}{{ resourse.download }}" class="downcode" target="_blank" download="" data-id="274" title="">下载</a>
                            </li>
                    {% endfor %}
                    


                        </ul>
                    </div>
                    <div class="box mb40">
                        <h4>讲师提示</h4>
                        <div class="teacher-info">
                            <a href="" target="_blank">
                                <img src='{{ MEDIA_URL }}{{ course.teacher.image }}' width='80' height='80' />
                            </a>
        <span class="tit">
          <a href="/u/315464/courses?sort=publish" target="_blank">{{ course.teacher.name }}</a>
        </span>
                            <span class="job">{{ course.teacher.work_position }}</span>
                        </div>
                        <div class="course-info-tip">
                            <dl class="first">
                                <dt>课程须知</dt>
                                <dd class="autowrap">{{ course.youneed_konw }}</dd>
                            </dl>
                            <dl>
                                <dt>老师告诉你能学到什么？</dt>
                                <dd class="autowrap">{{ course.teacher_tell }}</dd>
                            </dl>
                        </div>
                    </div>
                    <div class="cp-other-learned  js-comp-tabs">
                        <div class="cp-header clearfix">
                            <h2 class="cp-tit l">该课的同学还学过</h2>
                        </div>
                        <div class="cp-body">
                            <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="course" style="display: block">
                                <!-- img 200 x 112 -->
                                <ul class="other-list">
                            {% for relate_course in relate_courses %}
                                  <li class="curr">
                                        <a href="{% url 'course:detail' relate_course.id %}" target="_blank">
                                            <img src="{{ MEDIA_URL }}{{ relate_course.image }}" alt="{{ relate_course.name }}">
                                            <span class="name autowrap">{{ relate_course.name }}</span>
                                        </a>
                                    </li>
                            {% endfor %}



                                </ul>
                            </div>
                            <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="plan">
                                <ul class="other-list">
                                    <li class="curr">
                                        <a href="/course/programdetail/pid/31?src=sug" target="_blank">
                                            <img src="http://img.mukewang.com/56551e6700018b0c09600720-240-135.jpg" alt="Java工程师">
                                            <span class="name autowrap">Java工程师</span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <div class="clear"></div>

    </div>

</div>


</div>

{% endblock %}
{% block self_css %}
<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>公开课视频信息 - 慕学在线网</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/animate.css">
	<link rel="stylesheet" type="text/css" href="/static/css/style.css">

    <link rel="stylesheet" type="text/css" href="/static/css/muke/base.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/muke/common-less.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/muke/course/learn-less.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/aui.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/mooc.css" />
     <link rel="stylesheet" type="text/css" href="/static/css/muke/course/common-less.css">

    <script src="/static/js/jquery.min.js" type="text/javascript"></script>
    <script src="/static/js/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>

</head>
{% endblock %}



mxonline/templates/index.html

{% extends 'base.html' %}
{% load staticfiles %}

{% load staticfiles %}
{% block self_js %}
<script src="/static/js/selectUi.js" type='text/javascript'></script>
<script src="/static/js/deco-common.js" type='text/javascript'></script>
<script type="text/javascript" src="/static/js/plugins/laydate/laydate.js"></script>
<script src="/static/js/plugins/layer/layer.js"></script>
<script src="/static/js/plugins/queryCity/js/public.js" type="text/javascript"></script>
<script src="/static/js/unslider.js" type="text/javascript"></script>
<script src="/static/js/plugins/jquery.scrollLoading.js"  type="text/javascript"></script>
<script src="/static/js/deco-common.js"  type="text/javascript"></script>
<script type="text/javascript" src="/static/js/index.js"></script>

{% endblock %}
{% block self_css %}
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>募学在线网首页</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/animate.css">
	<link rel="stylesheet" type="text/css" href="/static/css/style.css">

    <script src="/static/js/jquery.min.js" type="text/javascript"></script>
    <script src="/static/js/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>

{% endblock %}

{% block custom_bread %}

{% endblock %}


{% block title %}
募学在线网首页
{% endblock %}

{% block content %}

    <div class="banner">
			<div class="wp">
				<div class="fl">
					<div class="imgslide">
						<ul class="imgs">
{% for banner in all_banners %}

                            <li>
                                    <a href="{{ banner.url }}">
                                        <img width="1200" height="478" src="{{ MEDIA_URL }}{{ banner.image }}" />
                                    </a>
                                </li>
{% endfor %}




						</ul>
					</div>
					<div class="unslider-arrow prev"></div>
					<div class="unslider-arrow next"></div>
				</div>

				</div>


			</div>
<!--banner end-->
<!--feature start-->
	<section>
		<div class="wp">
			<ul class="feature">
				<li class="feature1">
					<img class="pic" src="/static/images/feature1.png"/>
					<p class="center">专业权威</p>
				</li>
				<li class="feature2">
					<img class="pic" src="/static/images/feature2.png"/>
					<p class="center">课程最新</p>
				</li>
				<li class="feature3">
					<img class="pic" src="/static/images/feature3.png"/>
					<p class="center">名师授课</p>
				</li>
				<li class="feature4">
					<img class="pic" src="/static/images/feature4.png"/>
					<p class="center">数据真实</p>
				</li>
			</ul>
		</div>
	</section>
<!--feature end-->
<!--module1 start-->
	<section>
		<div class="module">
			<div class="wp">
				<h1>公开课程</h1>
				<div class="module1 eachmod">
					<div class="module1_1 left">
						<img width="228" height="614" src="/static/images/module1_1.jpg"/>
						<p class="fisrt_word">名师授课<br/>专业权威</p>
						<a class="more" href="course-list.html">查看更多课程 ></a>
					</div>
					<div class="right group_list">
						<div class="module1_2 box">
							<div class="imgslide2">
								<ul class="imgs">
{% for course in banner_course %}

                                    <li>
                                        <a href="{% url 'course:detail' course.id %}">
                                            <img width="470" height="300" src="{{ MEDIA_URL }}{{ course.image }}" />
                                        </a>
                                    </li>

{% endfor %}



								</ul>
							</div>
							<div class="unslider-arrow2 prev"></div>
							<div class="unslider-arrow2 next"></div>
						</div>
                {% for course in courses %}
                    <div class="module1_{{ forloop.counter|add:2 }} box">
                        <a href="{% url 'course:detail' course.id %}">
                                    <img width="233" height="190" src="{{ MEDIA_URL }}{{ course.image }}"/>
                                </a>
                                <div class="des">
                                    <a href="course-detail.html">
                                        <h2 title="django入门">{{ course.name }}</h2>
                                    </a>
                                    <span class="fl">难度：<i class="key">{{ course.get_degree_display }}</i></span>
                                    <span class="fr">学习人数：{{ course.students }}</span>
                                </div>
                                <div class="bottom">
                                    <span class="fl" title="慕课网">{{ course.org }}</span>
                                    <span class="star fr">0</span>
                                </div>
                            </div>

                {% endfor %}

					</div>
				</div>
			</div>
		</div>
	</section>
	<section>
		<div class="module greybg">
			<div class="wp">
				<h1>课程机构</h1>
				<div class="module3 eachmod">
					<div class="module3_1 left">
						<img width="228" height="463" src="/static/images/module3_1.jpg"/>
						<p class="fisrt_word">名校来袭<br/>权威认证</p>
						<a class="more" href="{% url 'org:list' %}">查看更多机构 ></a>
					</div>
					<div class="right">
						<ul>
{% for org in course_orgs %}

    <li class="{% if forloop.counter|divisibleby:5 %}
    five
    {% endif %}">
                                    <a href="{% url 'org:org_home' org.id %}">
                                        <div class="company">
                                            <img width="184" height="100" src="{{ MEDIA_URL }}{{ org.image }}"/>
                                            <div class="score">
                                                <div class="circle">
                                                    <h2>{{ org.tag }}</h2>
                                                </div>
                                            </div>
                                        </div>
                                        <p><span class="key" title="慕课网">{{ org.name }}</span></p>
                                    </a>
                                </li>



{% endfor %}



						</ul>
					</div>
				</div>
			</div>
		</div>
	</section>

{% endblock %}




mxonline/templates/org-detail-course.html
{% extends 'org_base.html' %}
{% load staticfiles %}

{% block title %}
机构课程
{% endblock %}

{% block page_path %}
			机构课程
			{% endblock %}
{% block right_form %}
<div class="right companycenter layout" >
		<div class="head">
			<h1>机构课程</h1>
		</div>
		<div class="brief group_list">
            {% for course in all_courses %}
            <div class="module1_5 box">
                    <a class="comp-img-box" href="course-detail.html">

                        <img width="214" height="195" src="{{ MEDIA_URL }}{{ course.image }}"/>
                    </a>
                    <div class="des">
                        <a href="course-detail.html"><h2>{{ course.name }}</h2></a>
                        <span class="fl">课时：{{ course.learn_time }}<i class="key">0</i></span>
                        <span class="fr">学习人数：{{ course.students }}</span>
                    </div>
                    <div class="bottom">
                        <span class="fl">{{ course_org.name }}</span>
                         <span class="star fr  notlogin
                            " data-favid="13" data-fav-type="4">
                            0
                        </span>
                    </div>
                </div>
            {% endfor %}


            </div>
			<div class="pageturn">
                <ul class="pagelist">
                    <li class="active"><a href="?page=1">1</a></li>
                </ul>
            </div>
</div>


{% endblock %}

mxonline/templates/org-detail-desc.html
{% extends 'org_base.html' %}
{% load staticfiles %}

{% block title %}
机构介绍
{% endblock %}

{% block page_path %}
		机构介绍
			{% endblock %}
{% block right_form %}
<div class="right companycenter layout" >
        <div class="head">
            <h1>机构介绍</h1>
        </div>
        <div class="des">
            <p>&nbsp;&nbsp;{{ all_desc }}</p>


        </div>
    </div>

{% endblock %}

mxonline/templates/password_reset.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
	<title>密码修改</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/animate.css">
	<link rel="stylesheet" type="text/css" href="/static/css/style.css">

<body>
<div class="wp">
    <div class="resetpassword" id="resetPwdForm">
        <h1>修改密码</h1>
        <p>已经通过验证，请设置新密码</p>
        <form id="reset_password_form" action="{% url 'modify_pwd' %}" method="post">
            <ul>
                <li>
                    <span class="">新 密 码 ：</span>
                    <input type="password" name="password1" id="pwd" placeholder="6-20位非中文字符">
                    <i></i>
                </li>
                <input type="hidden" name="email" value="{{ email }}">
                <li>
                    <span class="">确定密码：</span>
                    <input type="password" name="password2" id="repwd" placeholder="6-20位非中文字符">
                    <i></i>
                </li>
                <li class="button">
                    <input type="submit" value="提交" >
                </li>
            </ul>
            {% csrf_token %}
        </form>
    </div>
    <div class="resetpassword" id="reset_password_tips" style="display:none;">
        <h1>修改密码成功,请重新登录</h1>
        <img class="fl" src="/static/images/check2.png">
        <p class="successword">已经成功修改密码，请重新登录</p>
    </div>
</div>
</body>
</html>

mxonline/templates/send_fail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>邮件发送失败</title>
</head>
<body>
<p>邮件发送失败</p>
</body>
</html>

mxonline/templates/send_successs.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>邮件发送成功</p>
</body>
</html>

mxonline/templates/usercenter-fav-teacher.html

{% extends 'usercenterbase.html' %}
{% block right_content %}



    <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>
            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                      <li  {% if request.path|slice:'19' == '/usercenter/fav_org' %}
                        class="active"
                        {% endif %} ><a href="{% url 'usercenter:fav_org' user.id %}">课程机构</a> </li>
                        <li {% if request.path|slice:'23' == '/usercenter/fav_teacher' %}
                        class="active"
                        {% endif %} ><a href="{% url 'usercenter:fav_teacher' user.id %}">授课教师 </a></li>
                        <li {% if request.path|slice:'22' == '/usercenter/fav_course' %}
                        class="active"
                        {% endif %} ><a href="{% url 'usercenter:fav_course' user.id %}">公开课程</a></li>
                    </ul>
                </div>
                <div class="messagelist">
        {% for teacher in teachers %}

                    <div class=" butler_list butler-fav-box">
                        <dl class="des users">
                            <dt>
                                <a href="{% url 'org:teacher_detail' teacher.id %}">
                                    <img width="100" height="100" src="{{ MEDIA_URL }}{{ teacher.image }}"/>
                                </a>
                            </dt>
                            <dd>
                                <h1>
                                    <a href="{% url 'org:teacher_detail' teacher.id %}">
                                        {{ teacher.name }}<span class="key">认证教师</span>
                                    </a>
                                </h1>
                                <ul class="cont clearfix">
                                    <li class="time">工作年限：<span>{{ teacher.work_years }}年</span></li>
                                    <li class="c7">课程数：<span>{{ teacher.course_set.all.count }}</span></li>
                                </ul>
                                <ul class="cont clearfix">
                                    <li class="time">工作公司：<span>{{ teacher.work_company }}</span></li>
                                    <li class="c7">公司职位：<span>{{ teacher.work_position }}</span></li>
                                </ul>
                            </dd>
                            <div class="delete jsDeleteFav_teacher" data-favid="{{ teacher.id }}"></div>
                        </dl>
                    </div>

        {% endfor %}

                </div>
            </div>
        </div>


{% endblock %}


